/**
********************************************************************************
* NOTE : Generated by ngx_shm_dict_code. It is NOT supposed to modify this file.
*******************************************************************************/
#include "ngx_shm_dict_code.h"
#include "ngx_shm_dict_reader.h"
#include "ngx_shm_dict_writer.h"

static void ngx_shm_dict_from_int8(const int8_t * src, ngx_str_t * dst)
{
    dst->len = sizeof(int8_t);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_uint8(const uint8_t * src, ngx_str_t * dst)
{
    dst->len = sizeof(uint8_t);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_int16(const int16_t * src, ngx_str_t * dst)
{
    dst->len = sizeof(int16_t);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_uint16(const uint16_t * src, ngx_str_t * dst)
{
    dst->len = sizeof(uint16_t);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_int32(const int32_t * src, ngx_str_t * dst)
{
    dst->len = sizeof(int32_t);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_uint32(const uint32_t * src, ngx_str_t * dst)
{
    dst->len = sizeof(uint32_t);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_int64(const int64_t * src, ngx_str_t * dst)
{
    dst->len = sizeof(int64_t);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_uint64(const uint64_t * src, ngx_str_t * dst)
{
    dst->len = sizeof(uint64_t);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_double(const double * src, ngx_str_t * dst)
{
    dst->len = sizeof(double);
    dst->data = (u_char *)src;
}

static void ngx_shm_dict_from_string(const ngx_str_t * src, ngx_str_t * dst)
{
    dst->len = src->len;
    dst->data = (u_char *) src->data;
}

static void ngx_shm_dict_from_binary(const ngx_binary_t * src, ngx_str_t * dst)
{
    dst->len = src->len;
    dst->data = (u_char *) src->data;
}

static int ngx_shm_dict_to_int8(const ngx_str_t * src, int8_t * dst)
{
    *dst = *((int8_t *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_uint8(const ngx_str_t * src, uint8_t * dst)
{
    *dst = *((uint8_t *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_int16(const ngx_str_t * src, int16_t * dst)
{
    *dst = *((int16_t *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_uint16(const ngx_str_t * src, uint16_t * dst)
{
    *dst = *((uint16_t *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_int32(const ngx_str_t * src, int32_t * dst)
{
    *dst = *((int32_t *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_uint32(const ngx_str_t * src, uint32_t * dst)
{
    *dst = *((uint32_t *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_int64(const ngx_str_t * src, int64_t * dst)
{
    *dst = *((int64_t *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_uint64(const ngx_str_t * src, uint64_t * dst)
{
    *dst = *((uint64_t *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_double(const ngx_str_t * src, double * dst)
{
    *dst = *((double *) src->data);
    return NGX_OK;
}

static int ngx_shm_dict_to_string(const ngx_str_t * src, ngx_pool_t * pool, ngx_str_t * dst)
{
    return ngx_shm_dict_copy_str(src, pool, dst);
}

static int ngx_shm_dict_to_binary(const ngx_str_t * src, ngx_pool_t * pool, ngx_binary_t * dst)
{
    return ngx_shm_dict_copy_bin(src, pool, dst);
}

static int ngx_shm_dict_get_int8_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_int8(data, (int8_t *)val);
}

static int ngx_shm_dict_get_uint8_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_uint8(data, (uint8_t *)val);
}

static int ngx_shm_dict_get_int16_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_int16(data, (int16_t *)val);
}

static int ngx_shm_dict_get_uint16_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_uint16(data, (uint16_t *)val);
}

static int ngx_shm_dict_get_int32_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_int32(data, (int32_t *)val);
}

static int ngx_shm_dict_get_uint32_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_uint32(data, (uint32_t *)val);
}

static int ngx_shm_dict_get_int64_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_int64(data, (int64_t *)val);
}

static int ngx_shm_dict_get_uint64_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_uint64(data, (uint64_t *)val);
}

static int ngx_shm_dict_get_double_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_double(data, (double *)val);
}

static int ngx_shm_dict_get_string_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_string(data, (ngx_pool_t *)ctx, (ngx_str_t *)val);
}

static int ngx_shm_dict_get_binary_val(const ngx_str_t * data, void * ctx, void * val)
{
    return ngx_shm_dict_to_binary(data, (ngx_pool_t *)ctx, (ngx_binary_t *)val);
}

int ngx_shm_dict_get_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_INT8, ngx_shm_dict_get_int8_val, NULL, val);
}

int ngx_shm_dict_get_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_UINT8, ngx_shm_dict_get_uint8_val, NULL, val);
}

int ngx_shm_dict_get_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_INT16, ngx_shm_dict_get_int16_val, NULL, val);
}

int ngx_shm_dict_get_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_UINT16, ngx_shm_dict_get_uint16_val, NULL, val);
}

int ngx_shm_dict_get_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_INT32, ngx_shm_dict_get_int32_val, NULL, val);
}

int ngx_shm_dict_get_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_UINT32, ngx_shm_dict_get_uint32_val, NULL, val);
}

int ngx_shm_dict_get_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_INT64, ngx_shm_dict_get_int64_val, NULL, val);
}

int ngx_shm_dict_get_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_UINT64, ngx_shm_dict_get_uint64_val, NULL, val);
}

int ngx_shm_dict_get_double(ngx_shm_zone_t * zone, ngx_str_t * key, double * val)
{
    return ngx_shm_dict_get_base(zone, key, SHM_DICT_DOUBLE, ngx_shm_dict_get_double_val, NULL, val);
}

int ngx_shm_dict_get_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_pool_t * pool, ngx_str_t * val)
{
    return pool ? ngx_shm_dict_get_base(zone, key, SHM_DICT_STRING, ngx_shm_dict_get_string_val, pool, val) : NGX_ERROR;
}

int ngx_shm_dict_get_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_pool_t * pool, ngx_binary_t * val)
{
    return pool ? ngx_shm_dict_get_base(zone, key, SHM_DICT_BINARY, ngx_shm_dict_get_binary_val, pool, val) : NGX_ERROR;
}

int ngx_shm_dict_add_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int8(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_INT8, expire, 0);
}

int ngx_shm_dict_add_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint8(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_UINT8, expire, 0);
}

int ngx_shm_dict_add_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int16(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_INT16, expire, 0);
}

int ngx_shm_dict_add_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint16(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_UINT16, expire, 0);
}

int ngx_shm_dict_add_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int32(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_INT32, expire, 0);
}

int ngx_shm_dict_add_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint32(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_UINT32, expire, 0);
}

int ngx_shm_dict_add_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int64(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_INT64, expire, 0);
}

int ngx_shm_dict_add_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint64(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_UINT64, expire, 0);
}

int ngx_shm_dict_add_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_double(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_DOUBLE, expire, 0);
}

int ngx_shm_dict_add_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_string(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_STRING, expire, 0);
}

int ngx_shm_dict_add_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_binary(&val, &data);
    return ngx_shm_dict_add(zone, key, &data, SHM_DICT_BINARY, expire, 0);
}

int ngx_shm_dict_safe_add_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int8(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_INT8, expire, 0);
}

int ngx_shm_dict_safe_add_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint8(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_UINT8, expire, 0);
}

int ngx_shm_dict_safe_add_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int16(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_INT16, expire, 0);
}

int ngx_shm_dict_safe_add_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint16(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_UINT16, expire, 0);
}

int ngx_shm_dict_safe_add_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int32(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_INT32, expire, 0);
}

int ngx_shm_dict_safe_add_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint32(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_UINT32, expire, 0);
}

int ngx_shm_dict_safe_add_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int64(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_INT64, expire, 0);
}

int ngx_shm_dict_safe_add_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint64(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_UINT64, expire, 0);
}

int ngx_shm_dict_safe_add_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_double(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_DOUBLE, expire, 0);
}

int ngx_shm_dict_safe_add_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_string(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_STRING, expire, 0);
}

int ngx_shm_dict_safe_add_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_binary(&val, &data);
    return ngx_shm_dict_safe_add(zone, key, &data, SHM_DICT_BINARY, expire, 0);
}

int ngx_shm_dict_replace_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int8(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_INT8, expire, 0);
}

int ngx_shm_dict_replace_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint8(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_UINT8, expire, 0);
}

int ngx_shm_dict_replace_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int16(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_INT16, expire, 0);
}

int ngx_shm_dict_replace_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint16(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_UINT16, expire, 0);
}

int ngx_shm_dict_replace_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int32(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_INT32, expire, 0);
}

int ngx_shm_dict_replace_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint32(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_UINT32, expire, 0);
}

int ngx_shm_dict_replace_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int64(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_INT64, expire, 0);
}

int ngx_shm_dict_replace_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint64(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_UINT64, expire, 0);
}

int ngx_shm_dict_replace_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_double(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_DOUBLE, expire, 0);
}

int ngx_shm_dict_replace_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_string(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_STRING, expire, 0);
}

int ngx_shm_dict_replace_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_binary(&val, &data);
    return ngx_shm_dict_replace(zone, key, &data, SHM_DICT_BINARY, expire, 0);
}

int ngx_shm_dict_set_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int8(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_INT8, expire, 0);
}

int ngx_shm_dict_set_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint8(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_UINT8, expire, 0);
}

int ngx_shm_dict_set_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int16(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_INT16, expire, 0);
}

int ngx_shm_dict_set_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint16(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_UINT16, expire, 0);
}

int ngx_shm_dict_set_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int32(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_INT32, expire, 0);
}

int ngx_shm_dict_set_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint32(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_UINT32, expire, 0);
}

int ngx_shm_dict_set_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int64(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_INT64, expire, 0);
}

int ngx_shm_dict_set_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint64(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_UINT64, expire, 0);
}

int ngx_shm_dict_set_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_double(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_DOUBLE, expire, 0);
}

int ngx_shm_dict_set_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_string(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_STRING, expire, 0);
}

int ngx_shm_dict_set_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_binary(&val, &data);
    return ngx_shm_dict_set(zone, key, &data, SHM_DICT_BINARY, expire, 0);
}

int ngx_shm_dict_safe_set_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int8(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_INT8, expire, 0);
}

int ngx_shm_dict_safe_set_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint8(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_UINT8, expire, 0);
}

int ngx_shm_dict_safe_set_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int16(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_INT16, expire, 0);
}

int ngx_shm_dict_safe_set_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint16(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_UINT16, expire, 0);
}

int ngx_shm_dict_safe_set_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int32(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_INT32, expire, 0);
}

int ngx_shm_dict_safe_set_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint32(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_UINT32, expire, 0);
}

int ngx_shm_dict_safe_set_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_int64(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_INT64, expire, 0);
}

int ngx_shm_dict_safe_set_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_uint64(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_UINT64, expire, 0);
}

int ngx_shm_dict_safe_set_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_double(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_DOUBLE, expire, 0);
}

int ngx_shm_dict_safe_set_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_string(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_STRING, expire, 0);
}

int ngx_shm_dict_safe_set_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire)
{
    ngx_str_t data;
    ngx_shm_dict_from_binary(&val, &data);
    return ngx_shm_dict_safe_set(zone, key, &data, SHM_DICT_BINARY, expire, 0);
}

int ngx_shm_dict_incr_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t delta, uint32_t expire, int8_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_INT8;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_INT8)
        {
            return NGX_ERROR;
        }
        int8_t * val = (int8_t *) data.data;
        *result = __sync_add_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_int8(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_incr_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t delta, uint32_t expire, uint8_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_UINT8;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_UINT8)
        {
            return NGX_ERROR;
        }
        uint8_t * val = (uint8_t *) data.data;
        *result = __sync_add_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_uint8(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_incr_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t delta, uint32_t expire, int16_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_INT16;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_INT16)
        {
            return NGX_ERROR;
        }
        int16_t * val = (int16_t *) data.data;
        *result = __sync_add_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_int16(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_incr_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t delta, uint32_t expire, uint16_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_UINT16;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_UINT16)
        {
            return NGX_ERROR;
        }
        uint16_t * val = (uint16_t *) data.data;
        *result = __sync_add_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_uint16(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_incr_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t delta, uint32_t expire, int32_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_INT32;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_INT32)
        {
            return NGX_ERROR;
        }
        int32_t * val = (int32_t *) data.data;
        *result = __sync_add_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_int32(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_incr_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t delta, uint32_t expire, uint32_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_UINT32;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_UINT32)
        {
            return NGX_ERROR;
        }
        uint32_t * val = (uint32_t *) data.data;
        *result = __sync_add_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_uint32(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_incr_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t delta, uint32_t expire, int64_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_INT64;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_INT64)
        {
            return NGX_ERROR;
        }
        int64_t * val = (int64_t *) data.data;
        *result = __sync_add_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_int64(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_incr_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t delta, uint32_t expire, uint64_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_UINT64;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_UINT64)
        {
            return NGX_ERROR;
        }
        uint64_t * val = (uint64_t *) data.data;
        *result = __sync_add_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_uint64(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_incr_double(ngx_shm_zone_t * zone, ngx_str_t * key, double delta, uint32_t expire, double * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_DOUBLE;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_DOUBLE)
        {
            return NGX_ERROR;
        }
        ngx_shm_dict_ctx_t * ctx = zone->data;
        ngx_shmtx_lock(&ctx->shpool->mutex);
        double * val = (double *) data.data;
        *result = (*val += delta);
        ngx_shmtx_unlock(&ctx->shpool->mutex);
    }
    else
    {
        ngx_shm_dict_from_double(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t delta, uint32_t expire, int8_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_INT8;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_INT8)
        {
            return NGX_ERROR;
        }
        int8_t * val = (int8_t *) data.data;
        *result = __sync_sub_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_int8(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t delta, uint32_t expire, uint8_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_UINT8;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_UINT8)
        {
            return NGX_ERROR;
        }
        uint8_t * val = (uint8_t *) data.data;
        *result = __sync_sub_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_uint8(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t delta, uint32_t expire, int16_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_INT16;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_INT16)
        {
            return NGX_ERROR;
        }
        int16_t * val = (int16_t *) data.data;
        *result = __sync_sub_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_int16(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t delta, uint32_t expire, uint16_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_UINT16;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_UINT16)
        {
            return NGX_ERROR;
        }
        uint16_t * val = (uint16_t *) data.data;
        *result = __sync_sub_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_uint16(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t delta, uint32_t expire, int32_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_INT32;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_INT32)
        {
            return NGX_ERROR;
        }
        int32_t * val = (int32_t *) data.data;
        *result = __sync_sub_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_int32(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t delta, uint32_t expire, uint32_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_UINT32;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_UINT32)
        {
            return NGX_ERROR;
        }
        uint32_t * val = (uint32_t *) data.data;
        *result = __sync_sub_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_uint32(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t delta, uint32_t expire, int64_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_INT64;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_INT64)
        {
            return NGX_ERROR;
        }
        int64_t * val = (int64_t *) data.data;
        *result = __sync_sub_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_int64(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t delta, uint32_t expire, uint64_t * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_UINT64;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_UINT64)
        {
            return NGX_ERROR;
        }
        uint64_t * val = (uint64_t *) data.data;
        *result = __sync_sub_and_fetch(val, delta);
    }
    else
    {
        ngx_shm_dict_from_uint64(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}

int ngx_shm_dict_decr_double(ngx_shm_zone_t * zone, ngx_str_t * key, double delta, uint32_t expire, double * result)
{
    if (!zone || !key || !result)
    {
        return NGX_ERROR;
    }
    ngx_str_t data = ngx_null_string;
    uint8_t value_type = SHM_DICT_DOUBLE;
    ngx_int_t rc = ngx_shm_dict_get(zone, key, &data, &value_type, NULL, NULL);
    if (rc == NGX_OK)
    {
        if (value_type != SHM_DICT_DOUBLE)
        {
            return NGX_ERROR;
        }
        ngx_shm_dict_ctx_t * ctx = zone->data;
        ngx_shmtx_lock(&ctx->shpool->mutex);
        double * val = (double *) data.data;
        *result = (*val -= delta);
        ngx_shmtx_unlock(&ctx->shpool->mutex);
    }
    else
    {
        ngx_shm_dict_from_double(&delta, &data);
        rc = ngx_shm_dict_set(zone, key, &data, value_type, expire, 0);
        if (rc == NGX_OK)
        {
            *result = delta;
        }
    }
    return rc;
}
