/**
********************************************************************************
* NOTE : Generated by ngx_shm_dict_test. It is NOT supposed to modify this file.
*******************************************************************************/
#ifndef __ngx_shm_dict_test_20160121160004_h__
#define __ngx_shm_dict_test_20160121160004_h__

#include <ngx_http.h>
#include "ngx_shm_dict.h"
#include "ngx_shm_dict_test_utils.h"

ngx_int_t ngx_shm_dict_test_read(ngx_shm_dict_read_args_t * args, ngx_http_request_t * r);
ngx_int_t ngx_shm_dict_test_write(ngx_shm_dict_write_args_t * args);
ngx_int_t ngx_shm_dict_test_incr(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args);
ngx_int_t ngx_shm_dict_test_decr(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args);

#endif // __ngx_shm_dict_test_20160121160004_h__