/**
********************************************************************************
* NOTE : Generated by ngx_shm_dict_test. It is NOT supposed to modify this file.
*******************************************************************************/
#include "ngx_shm_dict_test.h"

static ngx_int_t __get_int8(ngx_str_t * key, ngx_http_request_t * r)
{
    int8_t val = 0;
    if (NGX_OK != ngx_shm_dict_get_int8(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_int(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_uint8(ngx_str_t * key, ngx_http_request_t * r)
{
    uint8_t val = 0;
    if (NGX_OK != ngx_shm_dict_get_uint8(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_uint(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_int16(ngx_str_t * key, ngx_http_request_t * r)
{
    int16_t val = 0;
    if (NGX_OK != ngx_shm_dict_get_int16(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_int(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_uint16(ngx_str_t * key, ngx_http_request_t * r)
{
    uint16_t val = 0;
    if (NGX_OK != ngx_shm_dict_get_uint16(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_uint(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_int32(ngx_str_t * key, ngx_http_request_t * r)
{
    int32_t val = 0;
    if (NGX_OK != ngx_shm_dict_get_int32(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_int(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_uint32(ngx_str_t * key, ngx_http_request_t * r)
{
    uint32_t val = 0;
    if (NGX_OK != ngx_shm_dict_get_uint32(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_uint(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_int64(ngx_str_t * key, ngx_http_request_t * r)
{
    int64_t val = 0;
    if (NGX_OK != ngx_shm_dict_get_int64(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_int(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_uint64(ngx_str_t * key, ngx_http_request_t * r)
{
    uint64_t val = 0;
    if (NGX_OK != ngx_shm_dict_get_uint64(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_uint(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_double(ngx_str_t * key, ngx_http_request_t * r)
{
    double val = 0.0;
    if (NGX_OK != ngx_shm_dict_get_double(ngx_shm_dict_test_get_zone(), key, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = ngx_shm_dict_test_from_double(r->pool, val);
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_int_t __get_string(ngx_str_t * key, ngx_http_request_t * r)
{
    ngx_str_t val = { 0, 0 };
    if (NGX_OK != ngx_shm_dict_get_string(ngx_shm_dict_test_get_zone(), key, r->pool, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    return ngx_http_send_response_imp(NGX_HTTP_OK, &val, r);
}

static ngx_int_t __get_binary(ngx_str_t * key, ngx_http_request_t * r)
{
    ngx_binary_t val = { 0, 0 };
    if (NGX_OK != ngx_shm_dict_get_binary(ngx_shm_dict_test_get_zone(), key, r->pool, &val))
    {
        return ngx_http_send_response_imp(NGX_HTTP_NOT_FOUND, NULL, r);
    }
    ngx_str_t response = { val.len, (u_char *)val.data };
    return ngx_http_send_response_imp(NGX_HTTP_OK, &response, r);
}

static ngx_shm_dict_test_read_item_t g_read_dict[] = {
    { ngx_string("int8"), __get_int8 },
    { ngx_string("uint8"), __get_uint8 },
    { ngx_string("int16"), __get_int16 },
    { ngx_string("uint16"), __get_uint16 },
    { ngx_string("int32"), __get_int32 },
    { ngx_string("uint32"), __get_uint32 },
    { ngx_string("int64"), __get_int64 },
    { ngx_string("uint64"), __get_uint64 },
    { ngx_string("double"), __get_double },
    { ngx_string("string"), __get_string },
    { ngx_string("binary"), __get_binary },
};
static size_t g_read_dict_len = sizeof(g_read_dict) / sizeof(ngx_shm_dict_test_read_item_t);
ngx_int_t ngx_shm_dict_test_read(ngx_shm_dict_read_args_t * args, ngx_http_request_t * r)
{
    return ngx_shm_dict_test_read_base(g_read_dict, g_read_dict_len, args, r);
}

static ngx_int_t __add_int8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int8_t val = (int8_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_add_int8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_uint8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint8_t val = (uint8_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_add_uint8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_int16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int16_t val = (int16_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_add_int16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_uint16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint16_t val = (uint16_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_add_uint16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_int32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int32_t val = (int32_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_add_int32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_uint32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint32_t val = (uint32_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_add_uint32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_int64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int64_t val = (int64_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_add_int64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_uint64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint64_t val = (uint64_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_add_uint64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_double(ngx_shm_dict_write_args_t * args)
{
    double val = (double) atof((const char *)args->val.data);
    return ngx_shm_dict_add_double(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_string(ngx_shm_dict_write_args_t * args)
{
    ngx_str_t val = args->val;
    return ngx_shm_dict_add_string(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __add_binary(ngx_shm_dict_write_args_t * args)
{
    ngx_binary_t val = { args->val.len, args->val.data };
    return ngx_shm_dict_add_binary(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_int8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int8_t val = (int8_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_add_int8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_uint8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint8_t val = (uint8_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_add_uint8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_int16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int16_t val = (int16_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_add_int16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_uint16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint16_t val = (uint16_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_add_uint16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_int32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int32_t val = (int32_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_add_int32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_uint32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint32_t val = (uint32_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_add_uint32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_int64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int64_t val = (int64_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_add_int64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_uint64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint64_t val = (uint64_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_add_uint64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_double(ngx_shm_dict_write_args_t * args)
{
    double val = (double) atof((const char *)args->val.data);
    return ngx_shm_dict_safe_add_double(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_string(ngx_shm_dict_write_args_t * args)
{
    ngx_str_t val = args->val;
    return ngx_shm_dict_safe_add_string(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_add_binary(ngx_shm_dict_write_args_t * args)
{
    ngx_binary_t val = { args->val.len, args->val.data };
    return ngx_shm_dict_safe_add_binary(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_int8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int8_t val = (int8_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_replace_int8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_uint8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint8_t val = (uint8_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_replace_uint8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_int16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int16_t val = (int16_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_replace_int16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_uint16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint16_t val = (uint16_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_replace_uint16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_int32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int32_t val = (int32_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_replace_int32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_uint32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint32_t val = (uint32_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_replace_uint32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_int64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int64_t val = (int64_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_replace_int64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_uint64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint64_t val = (uint64_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_replace_uint64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_double(ngx_shm_dict_write_args_t * args)
{
    double val = (double) atof((const char *)args->val.data);
    return ngx_shm_dict_replace_double(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_string(ngx_shm_dict_write_args_t * args)
{
    ngx_str_t val = args->val;
    return ngx_shm_dict_replace_string(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __replace_binary(ngx_shm_dict_write_args_t * args)
{
    ngx_binary_t val = { args->val.len, args->val.data };
    return ngx_shm_dict_replace_binary(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_int8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int8_t val = (int8_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_set_int8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_uint8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint8_t val = (uint8_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_set_uint8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_int16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int16_t val = (int16_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_set_int16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_uint16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint16_t val = (uint16_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_set_uint16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_int32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int32_t val = (int32_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_set_int32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_uint32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint32_t val = (uint32_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_set_uint32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_int64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int64_t val = (int64_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_set_int64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_uint64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint64_t val = (uint64_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_set_uint64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_double(ngx_shm_dict_write_args_t * args)
{
    double val = (double) atof((const char *)args->val.data);
    return ngx_shm_dict_set_double(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_string(ngx_shm_dict_write_args_t * args)
{
    ngx_str_t val = args->val;
    return ngx_shm_dict_set_string(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __set_binary(ngx_shm_dict_write_args_t * args)
{
    ngx_binary_t val = { args->val.len, args->val.data };
    return ngx_shm_dict_set_binary(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_int8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int8_t val = (int8_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_set_int8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_uint8(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint8_t val = (uint8_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_set_uint8(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_int16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int16_t val = (int16_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_set_int16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_uint16(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint16_t val = (uint16_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_set_uint16(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_int32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int32_t val = (int32_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_set_int32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_uint32(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint32_t val = (uint32_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_set_uint32(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_int64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    int64_t val = (int64_t) strtoll((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_set_int64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_uint64(ngx_shm_dict_write_args_t * args)
{
    char * tail = NULL;
    uint64_t val = (uint64_t) strtoull((const char *)args->val.data, &tail, 10);
    return ngx_shm_dict_safe_set_uint64(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_double(ngx_shm_dict_write_args_t * args)
{
    double val = (double) atof((const char *)args->val.data);
    return ngx_shm_dict_safe_set_double(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_string(ngx_shm_dict_write_args_t * args)
{
    ngx_str_t val = args->val;
    return ngx_shm_dict_safe_set_string(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_int_t __safe_set_binary(ngx_shm_dict_write_args_t * args)
{
    ngx_binary_t val = { args->val.len, args->val.data };
    return ngx_shm_dict_safe_set_binary(ngx_shm_dict_test_get_zone(), &args->key, val, args->expire);
}

static ngx_shm_dict_test_write_item_t g_write_dict[] = {
    { ngx_string("add"), ngx_string("int8"), __add_int8 },
    { ngx_string("add"), ngx_string("uint8"), __add_uint8 },
    { ngx_string("add"), ngx_string("int16"), __add_int16 },
    { ngx_string("add"), ngx_string("uint16"), __add_uint16 },
    { ngx_string("add"), ngx_string("int32"), __add_int32 },
    { ngx_string("add"), ngx_string("uint32"), __add_uint32 },
    { ngx_string("add"), ngx_string("int64"), __add_int64 },
    { ngx_string("add"), ngx_string("uint64"), __add_uint64 },
    { ngx_string("add"), ngx_string("double"), __add_double },
    { ngx_string("add"), ngx_string("string"), __add_string },
    { ngx_string("add"), ngx_string("binary"), __add_binary },
    { ngx_string("safe_add"), ngx_string("int8"), __safe_add_int8 },
    { ngx_string("safe_add"), ngx_string("uint8"), __safe_add_uint8 },
    { ngx_string("safe_add"), ngx_string("int16"), __safe_add_int16 },
    { ngx_string("safe_add"), ngx_string("uint16"), __safe_add_uint16 },
    { ngx_string("safe_add"), ngx_string("int32"), __safe_add_int32 },
    { ngx_string("safe_add"), ngx_string("uint32"), __safe_add_uint32 },
    { ngx_string("safe_add"), ngx_string("int64"), __safe_add_int64 },
    { ngx_string("safe_add"), ngx_string("uint64"), __safe_add_uint64 },
    { ngx_string("safe_add"), ngx_string("double"), __safe_add_double },
    { ngx_string("safe_add"), ngx_string("string"), __safe_add_string },
    { ngx_string("safe_add"), ngx_string("binary"), __safe_add_binary },
    { ngx_string("replace"), ngx_string("int8"), __replace_int8 },
    { ngx_string("replace"), ngx_string("uint8"), __replace_uint8 },
    { ngx_string("replace"), ngx_string("int16"), __replace_int16 },
    { ngx_string("replace"), ngx_string("uint16"), __replace_uint16 },
    { ngx_string("replace"), ngx_string("int32"), __replace_int32 },
    { ngx_string("replace"), ngx_string("uint32"), __replace_uint32 },
    { ngx_string("replace"), ngx_string("int64"), __replace_int64 },
    { ngx_string("replace"), ngx_string("uint64"), __replace_uint64 },
    { ngx_string("replace"), ngx_string("double"), __replace_double },
    { ngx_string("replace"), ngx_string("string"), __replace_string },
    { ngx_string("replace"), ngx_string("binary"), __replace_binary },
    { ngx_string("set"), ngx_string("int8"), __set_int8 },
    { ngx_string("set"), ngx_string("uint8"), __set_uint8 },
    { ngx_string("set"), ngx_string("int16"), __set_int16 },
    { ngx_string("set"), ngx_string("uint16"), __set_uint16 },
    { ngx_string("set"), ngx_string("int32"), __set_int32 },
    { ngx_string("set"), ngx_string("uint32"), __set_uint32 },
    { ngx_string("set"), ngx_string("int64"), __set_int64 },
    { ngx_string("set"), ngx_string("uint64"), __set_uint64 },
    { ngx_string("set"), ngx_string("double"), __set_double },
    { ngx_string("set"), ngx_string("string"), __set_string },
    { ngx_string("set"), ngx_string("binary"), __set_binary },
    { ngx_string("safe_set"), ngx_string("int8"), __safe_set_int8 },
    { ngx_string("safe_set"), ngx_string("uint8"), __safe_set_uint8 },
    { ngx_string("safe_set"), ngx_string("int16"), __safe_set_int16 },
    { ngx_string("safe_set"), ngx_string("uint16"), __safe_set_uint16 },
    { ngx_string("safe_set"), ngx_string("int32"), __safe_set_int32 },
    { ngx_string("safe_set"), ngx_string("uint32"), __safe_set_uint32 },
    { ngx_string("safe_set"), ngx_string("int64"), __safe_set_int64 },
    { ngx_string("safe_set"), ngx_string("uint64"), __safe_set_uint64 },
    { ngx_string("safe_set"), ngx_string("double"), __safe_set_double },
    { ngx_string("safe_set"), ngx_string("string"), __safe_set_string },
    { ngx_string("safe_set"), ngx_string("binary"), __safe_set_binary },
};
static size_t g_write_dict_len = sizeof(g_write_dict) / sizeof(ngx_shm_dict_test_write_item_t);
ngx_int_t ngx_shm_dict_test_write(ngx_shm_dict_write_args_t * args)
{
    return ngx_shm_dict_test_write_base(g_write_dict, g_write_dict_len, args);
}
static ngx_int_t __incr_int8(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    int8_t delta = (int8_t) strtoll((const char *)args->delta.data, &tail, 10);
    int8_t result = 0;
    int rc = ngx_shm_dict_incr_int8(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_int(pool, result);
    return NGX_OK;
}

static ngx_int_t __incr_uint8(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    uint8_t delta = (uint8_t) strtoull((const char *)args->delta.data, &tail, 10);
    uint8_t result = 0;
    int rc = ngx_shm_dict_incr_uint8(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_uint(pool, result);
    return NGX_OK;
}

static ngx_int_t __incr_int16(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    int16_t delta = (int16_t) strtoll((const char *)args->delta.data, &tail, 10);
    int16_t result = 0;
    int rc = ngx_shm_dict_incr_int16(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_int(pool, result);
    return NGX_OK;
}

static ngx_int_t __incr_uint16(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    uint16_t delta = (uint16_t) strtoull((const char *)args->delta.data, &tail, 10);
    uint16_t result = 0;
    int rc = ngx_shm_dict_incr_uint16(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_uint(pool, result);
    return NGX_OK;
}

static ngx_int_t __incr_int32(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    int32_t delta = (int32_t) strtoll((const char *)args->delta.data, &tail, 10);
    int32_t result = 0;
    int rc = ngx_shm_dict_incr_int32(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_int(pool, result);
    return NGX_OK;
}

static ngx_int_t __incr_uint32(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    uint32_t delta = (uint32_t) strtoull((const char *)args->delta.data, &tail, 10);
    uint32_t result = 0;
    int rc = ngx_shm_dict_incr_uint32(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_uint(pool, result);
    return NGX_OK;
}

static ngx_int_t __incr_int64(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    int64_t delta = (int64_t) strtoll((const char *)args->delta.data, &tail, 10);
    int64_t result = 0;
    int rc = ngx_shm_dict_incr_int64(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_int(pool, result);
    return NGX_OK;
}

static ngx_int_t __incr_uint64(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    uint64_t delta = (uint64_t) strtoull((const char *)args->delta.data, &tail, 10);
    uint64_t result = 0;
    int rc = ngx_shm_dict_incr_uint64(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_uint(pool, result);
    return NGX_OK;
}

static ngx_int_t __incr_double(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    double delta = (double) atof((const char *)args->delta.data);
    double result = 0;
    int rc = ngx_shm_dict_incr_double(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_double(pool, result);
    return NGX_OK;
}

static ngx_shm_dict_test_mod_item_t g_incr_dict[] = {
    { ngx_string("int8"), __incr_int8 },
    { ngx_string("uint8"), __incr_uint8 },
    { ngx_string("int16"), __incr_int16 },
    { ngx_string("uint16"), __incr_uint16 },
    { ngx_string("int32"), __incr_int32 },
    { ngx_string("uint32"), __incr_uint32 },
    { ngx_string("int64"), __incr_int64 },
    { ngx_string("uint64"), __incr_uint64 },
    { ngx_string("double"), __incr_double },
};
static size_t g_incr_dict_len = sizeof(g_incr_dict) / sizeof(ngx_shm_dict_test_mod_item_t);
ngx_int_t ngx_shm_dict_test_incr(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    return ngx_shm_dict_test_mod_base(g_incr_dict, g_incr_dict_len, pool, args);
}

static ngx_int_t __decr_int8(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    int8_t delta = (int8_t) strtoll((const char *)args->delta.data, &tail, 10);
    int8_t result = 0;
    int rc = ngx_shm_dict_decr_int8(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_int(pool, result);
    return NGX_OK;
}

static ngx_int_t __decr_uint8(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    uint8_t delta = (uint8_t) strtoull((const char *)args->delta.data, &tail, 10);
    uint8_t result = 0;
    int rc = ngx_shm_dict_decr_uint8(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_uint(pool, result);
    return NGX_OK;
}

static ngx_int_t __decr_int16(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    int16_t delta = (int16_t) strtoll((const char *)args->delta.data, &tail, 10);
    int16_t result = 0;
    int rc = ngx_shm_dict_decr_int16(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_int(pool, result);
    return NGX_OK;
}

static ngx_int_t __decr_uint16(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    uint16_t delta = (uint16_t) strtoull((const char *)args->delta.data, &tail, 10);
    uint16_t result = 0;
    int rc = ngx_shm_dict_decr_uint16(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_uint(pool, result);
    return NGX_OK;
}

static ngx_int_t __decr_int32(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    int32_t delta = (int32_t) strtoll((const char *)args->delta.data, &tail, 10);
    int32_t result = 0;
    int rc = ngx_shm_dict_decr_int32(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_int(pool, result);
    return NGX_OK;
}

static ngx_int_t __decr_uint32(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    uint32_t delta = (uint32_t) strtoull((const char *)args->delta.data, &tail, 10);
    uint32_t result = 0;
    int rc = ngx_shm_dict_decr_uint32(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_uint(pool, result);
    return NGX_OK;
}

static ngx_int_t __decr_int64(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    int64_t delta = (int64_t) strtoll((const char *)args->delta.data, &tail, 10);
    int64_t result = 0;
    int rc = ngx_shm_dict_decr_int64(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_int(pool, result);
    return NGX_OK;
}

static ngx_int_t __decr_uint64(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    char * tail = NULL;
    uint64_t delta = (uint64_t) strtoull((const char *)args->delta.data, &tail, 10);
    uint64_t result = 0;
    int rc = ngx_shm_dict_decr_uint64(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_uint(pool, result);
    return NGX_OK;
}

static ngx_int_t __decr_double(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    double delta = (double) atof((const char *)args->delta.data);
    double result = 0;
    int rc = ngx_shm_dict_decr_double(ngx_shm_dict_test_get_zone(), &args->key, delta, args->expire, &result);
    if (NGX_OK != rc)
    {
        return NGX_ERROR;
    }
    args->result = ngx_shm_dict_test_from_double(pool, result);
    return NGX_OK;
}

static ngx_shm_dict_test_mod_item_t g_decr_dict[] = {
    { ngx_string("int8"), __decr_int8 },
    { ngx_string("uint8"), __decr_uint8 },
    { ngx_string("int16"), __decr_int16 },
    { ngx_string("uint16"), __decr_uint16 },
    { ngx_string("int32"), __decr_int32 },
    { ngx_string("uint32"), __decr_uint32 },
    { ngx_string("int64"), __decr_int64 },
    { ngx_string("uint64"), __decr_uint64 },
    { ngx_string("double"), __decr_double },
};
static size_t g_decr_dict_len = sizeof(g_decr_dict) / sizeof(ngx_shm_dict_test_mod_item_t);
ngx_int_t ngx_shm_dict_test_decr(ngx_pool_t * pool, ngx_shm_dict_mod_args_t * args)
{
    return ngx_shm_dict_test_mod_base(g_decr_dict, g_decr_dict_len, pool, args);
}
