/**
********************************************************************************
* NOTE : Generated by ngx_shm_dict_code. It is NOT supposed to modify this file.
*******************************************************************************/
#ifndef __ngx_shm_dict_code_20160114154206_h__
#define __ngx_shm_dict_code_20160114154206_h__

#include "ngx_shm_dict_utils.h"

int ngx_shm_dict_get_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t * val);
int ngx_shm_dict_get_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t * val);
int ngx_shm_dict_get_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t * val);
int ngx_shm_dict_get_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t * val);
int ngx_shm_dict_get_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t * val);
int ngx_shm_dict_get_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t * val);
int ngx_shm_dict_get_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t * val);
int ngx_shm_dict_get_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t * val);
int ngx_shm_dict_get_double(ngx_shm_zone_t * zone, ngx_str_t * key, double * val);
int ngx_shm_dict_get_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_pool_t * pool, ngx_str_t * val);
int ngx_shm_dict_get_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_pool_t * pool, ngx_binary_t * val);

int ngx_shm_dict_add_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire);
int ngx_shm_dict_add_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire);
int ngx_shm_dict_add_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire);
int ngx_shm_dict_add_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire);
int ngx_shm_dict_add_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire);
int ngx_shm_dict_add_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire);
int ngx_shm_dict_add_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire);
int ngx_shm_dict_add_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire);
int ngx_shm_dict_add_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire);
int ngx_shm_dict_add_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire);
int ngx_shm_dict_add_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire);

int ngx_shm_dict_safe_add_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire);
int ngx_shm_dict_safe_add_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire);
int ngx_shm_dict_safe_add_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire);
int ngx_shm_dict_safe_add_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire);
int ngx_shm_dict_safe_add_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire);
int ngx_shm_dict_safe_add_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire);
int ngx_shm_dict_safe_add_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire);
int ngx_shm_dict_safe_add_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire);
int ngx_shm_dict_safe_add_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire);
int ngx_shm_dict_safe_add_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire);
int ngx_shm_dict_safe_add_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire);

int ngx_shm_dict_replace_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire);
int ngx_shm_dict_replace_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire);
int ngx_shm_dict_replace_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire);
int ngx_shm_dict_replace_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire);
int ngx_shm_dict_replace_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire);
int ngx_shm_dict_replace_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire);
int ngx_shm_dict_replace_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire);
int ngx_shm_dict_replace_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire);
int ngx_shm_dict_replace_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire);
int ngx_shm_dict_replace_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire);
int ngx_shm_dict_replace_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire);

int ngx_shm_dict_set_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire);
int ngx_shm_dict_set_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire);
int ngx_shm_dict_set_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire);
int ngx_shm_dict_set_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire);
int ngx_shm_dict_set_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire);
int ngx_shm_dict_set_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire);
int ngx_shm_dict_set_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire);
int ngx_shm_dict_set_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire);
int ngx_shm_dict_set_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire);
int ngx_shm_dict_set_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire);
int ngx_shm_dict_set_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire);

int ngx_shm_dict_safe_set_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t val, uint32_t expire);
int ngx_shm_dict_safe_set_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t val, uint32_t expire);
int ngx_shm_dict_safe_set_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t val, uint32_t expire);
int ngx_shm_dict_safe_set_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t val, uint32_t expire);
int ngx_shm_dict_safe_set_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t val, uint32_t expire);
int ngx_shm_dict_safe_set_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t val, uint32_t expire);
int ngx_shm_dict_safe_set_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t val, uint32_t expire);
int ngx_shm_dict_safe_set_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t val, uint32_t expire);
int ngx_shm_dict_safe_set_double(ngx_shm_zone_t * zone, ngx_str_t * key, double val, uint32_t expire);
int ngx_shm_dict_safe_set_string(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_str_t val, uint32_t expire);
int ngx_shm_dict_safe_set_binary(ngx_shm_zone_t * zone, ngx_str_t * key, ngx_binary_t val, uint32_t expire);

int ngx_shm_dict_incr_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t delta, uint32_t expire, int8_t * result);
int ngx_shm_dict_incr_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t delta, uint32_t expire, uint8_t * result);
int ngx_shm_dict_incr_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t delta, uint32_t expire, int16_t * result);
int ngx_shm_dict_incr_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t delta, uint32_t expire, uint16_t * result);
int ngx_shm_dict_incr_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t delta, uint32_t expire, int32_t * result);
int ngx_shm_dict_incr_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t delta, uint32_t expire, uint32_t * result);
int ngx_shm_dict_incr_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t delta, uint32_t expire, int64_t * result);
int ngx_shm_dict_incr_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t delta, uint32_t expire, uint64_t * result);
int ngx_shm_dict_incr_double(ngx_shm_zone_t * zone, ngx_str_t * key, double delta, uint32_t expire, double * result);

int ngx_shm_dict_decr_int8(ngx_shm_zone_t * zone, ngx_str_t * key, int8_t delta, uint32_t expire, int8_t * result);
int ngx_shm_dict_decr_uint8(ngx_shm_zone_t * zone, ngx_str_t * key, uint8_t delta, uint32_t expire, uint8_t * result);
int ngx_shm_dict_decr_int16(ngx_shm_zone_t * zone, ngx_str_t * key, int16_t delta, uint32_t expire, int16_t * result);
int ngx_shm_dict_decr_uint16(ngx_shm_zone_t * zone, ngx_str_t * key, uint16_t delta, uint32_t expire, uint16_t * result);
int ngx_shm_dict_decr_int32(ngx_shm_zone_t * zone, ngx_str_t * key, int32_t delta, uint32_t expire, int32_t * result);
int ngx_shm_dict_decr_uint32(ngx_shm_zone_t * zone, ngx_str_t * key, uint32_t delta, uint32_t expire, uint32_t * result);
int ngx_shm_dict_decr_int64(ngx_shm_zone_t * zone, ngx_str_t * key, int64_t delta, uint32_t expire, int64_t * result);
int ngx_shm_dict_decr_uint64(ngx_shm_zone_t * zone, ngx_str_t * key, uint64_t delta, uint32_t expire, uint64_t * result);
int ngx_shm_dict_decr_double(ngx_shm_zone_t * zone, ngx_str_t * key, double delta, uint32_t expire, double * result);

#endif // __ngx_shm_dict_code_20160114154206_h__